### ISSUE TITLE
new capture.py crash 

### ISSUE THREAD

**Issue by electronicmax** [OxfordHCC/IoT-refine#62]
![Screenshot 2019-07-03 at 16 49 39](https://user-images.githubusercontent.com/689563/60606628-95d54680-9db3-11e9-85be-41075625c8d5.png)

**Comment by electronicmax** [comment]
a slightly bigger screenshot oops

![Screenshot 2019-07-03 at 16 57 58](https://user-images.githubusercontent.com/689563/60606693-bac9b980-9db3-11e9-89da-1977b826e633.png)

**Comment by mcnutty26** [comment]
Fixed in 1db8adb56a9fe269354a972e93c394b2eeaea639
