### ISSUE TITLE
api.py get impacts broken or changed semantics

### ISSUE THREAD

**Issue by electronicmax** [OxfordHCC/IoT-refine#63]
topic:
calling impacts like http://localhost:4201/api/impacts/1563308962/1563308962/1

what it should do: 
should return the impacts from minute 1563308962 to 1563308962 inclusive, bucketed at 1 minute intervals

what it does instead
this returns an empty object for impacts, unless the start value is very small (e.g. 0 or 1000) 

this bug was created in the past week or so and seems to only affect timeseries (?)

**Comment by mcnutty26** [comment]
Will take a look tomorrow

**Comment by electronicmax** [comment]
UPDATE: It was a timezone bug! 
FIXED

**Comment by electronicmax** [comment]
in 3f56538
