### ISSUE TITLE
company info display needs a real database of company info

### ISSUE THREAD

**Issue by electronicmax** [OxfordHCC/IoT-refine#72]
(instead of just 6 sample entries!)

can we bring back the database that x-ray refine used?

**Comment by electronicmax** [comment]
Determining the crunchbase URL and popping up an iframe for that URL might be a workaround to trying to achieve critical mass here.  We sort of did this with X-Ray Refine

**Comment by mcnutty26** [comment]
The next part of the component gets data from Wikipedia if it's not in the array - I just added the array to make sure we catch companies that aren't easily searchable and are likely to come up.

**Comment by mcnutty26** [comment]
We could similarly add crunchbase to that - I'll take a look later on

**Comment by electronicmax** [comment]
new fix: the crunchbase window is pretty good. closing and opening new relevant issues pertaining to that
