### ISSUE TITLE
Time series doesn't scroll/paginate companies

### ISSUE THREAD

**Issue by mcnutty26** [OxfordHCC/IoT-refine#76]
The list gets too long and goes off the end

**Comment by mcnutty26** [comment]
![Screenshot 2019-07-25 at 15 28 46](https://user-images.githubusercontent.com/1874503/61882801-1a1d7400-aef1-11e9-9a56-ea842cdb423a.png)

**Comment by electronicmax** [comment]
resolved in eb24a0c . not a perfect solution but a bit better!
