### ISSUE TITLE
loop.py bug : most of geodata's domain column is 'unknown'

### ISSUE THREAD

**Issue by electronicmax** [OxfordHCC/IoT-refine#80]
something about our method to resolve IP to name (in geodata resolution) is not right, 90% of the entries are 'unknown'.  this makes using that field in the geodata db very difficult - which i'm trying to do to match companies.

any idea, @mcnutty26 ?

**Comment by mcnutty26** [comment]
Yeah, it's very inaccurate. This is more of a technical limitation though.

A lot of IP addresses don't have reverse pointers, and those that do will lead you to *one* of the domains associated with that IP. For the big players this isn't so bad, but anyone sharing a server might give weird/bad results. 

In an ideal world we would just do DPI :P I'll take a look at the Princeton code to see if there's anything else we can do.

**Comment by electronicmax** [comment]
there was a problem in the way that the dnsresolver library was being used. the unknowns went down from 80% to 30%, which is still high but better than nothing

**Comment by electronicmax** [comment]
i'm going to mark this as resolved for now! i think i can work with this.
